version: "3.9"

services:
  db:
    image: mysql:8.4
    platform: linux/amd64
    container_name: mose-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mose
      TZ: "Asia/Tokyo"
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql