version: "3.9"

services:
  db:
    image: postgres:17.3
    platform: linux/amd64
    container_name: mose-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: mose
      TZ: "Asia/Tokyo"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data